name: Deploy website

on: 
    push:
        branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Install Netlify
        run: cd vite-project && yarn install netlify-cli@17.10.1 -g

      - name: Install Dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
            --prod